### ISSUE TITLE
Support less 1.7.0's ability to pass rulesets to mixins.

### ISSUE THREAD

**Issue by TrisMcC** [purcell/less-css-mode#18]
http://lesscss.org/features/#detached-rulesets-feature

**Comment by ssbb** [comment]
+1, it is very much needed.

**Comment by purcell** [comment]
"Patches welcome" in this case, I'm sorry to say, at least until I find I need this myself. :-)

The current behaviour is mostly okay, but the failing case I see right now is the block indentation in this:

```
.desktop-and-old-ie(@rules) {
  @media screen and (min-width: 1200) { @rules(); }
  html.lt-ie9 &                       { @rules(); }
}

header {
  background-color: blue;

  .desktop-and-old-ie({
background-color: red;
});
}
```

It will need a modified `indent-line-function` and/or some additional SMIE rules.

**Comment by ssbb** [comment]
Just I am using Less for BEM-like naming and write few mixins for it:

```less
// Element
.e(@name, @rules) {
  &__@{name} { @rules(); }
}

// Modificator
.m(@name, @rules) {
  &--@{name} { @rules(); }
}

.btn {
  .e(span, {  // .btn__span
    display: inline-block;
  });
  .m(primary, { // .btn--primary
    background: blue;
  });
}
```

I found it very useful. But it is problematic when indentation are not working properly :(

I have tried to override `indent-line-function`, but unsuccessful.

I will try again, thanks :)

**Comment by ssbb** [comment]
Have no luck :( But I found that web-mode works pretty well with LESS CSS indentation for me.

```less
.desktop-and-old-ie(@rules) {
  @media screen and (min-width: 1200) { @rules(); }
  html.lt-ie9 &                       { @rules(); }
}

header {
  background-color: #ff0000;

  .desktop-and-old-ie({
    background-color: red;
  });
}

```
